export const SIGNUP_REQUEST = 'USER_SIGNUP_REQUEST';
export const SIGNUP_SUCCESS = 'USER_SIGNUP_SUCCESS';
export const SIGNUP_FAILURE = 'USER_SIGNUP_FAILURE';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOADING = 'LOADING';
export const LOGOUT = 'LOGOUT';
